# Generated by Django 3.2.4 on 2023-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='eno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
