# Generated by Django 3.2.4 on 2023-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_explore_eno'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppic', models.ImageField(null=True, upload_to='static/explorepic/')),
                ('pname', models.CharField(max_length=200, null=True)),
                ('pdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
