# Generated by Django 3.2.4 on 2023-10-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20231010_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='easytrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etpic', models.ImageField(null=True, upload_to='static/easytrippic/')),
                ('etname', models.CharField(max_length=200, null=True)),
                ('etdis', models.CharField(max_length=100, null=True)),
                ('etdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/propertypic/'),
        ),
    ]
