# Generated by Django 3.2.4 on 2023-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20231010_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='nexttrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntpic', models.ImageField(null=True, upload_to='static/nexttrippic')),
                ('ntname', models.CharField(max_length=200, null=True)),
                ('ntabout', models.CharField(max_length=500, null=True)),
                ('ntdate', models.DateField()),
            ],
        ),
    ]
