# Generated by Django 3.2.4 on 2023-10-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_uniprop'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeguest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgpic', models.ImageField(null=True, upload_to='static/homeguestpic')),
                ('hgname', models.CharField(max_length=200, null=True)),
                ('hglocation', models.CharField(max_length=500, null=True)),
                ('hgrating', models.FloatField(max_length=20, null=True)),
                ('hgreviews', models.CharField(max_length=200, null=True)),
                ('hgdate', models.DateField()),
            ],
        ),
    ]
