# Generated by Django 3.2.4 on 2023-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cmesge',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='cname',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cno',
        ),
        migrations.AddField(
            model_name='contact',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
    ]
