# Generated by Django 3.2.4 on 2023-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile',
            field=models.ImageField(null=True, upload_to='static/userpic/'),
        ),
    ]
