# Generated by Django 3.2.4 on 2023-10-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_register_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
