# Generated by Django 3.2.4 on 2023-12-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_register_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=100, null=True)),
                ('hotelName', models.CharField(max_length=500, null=True)),
                ('hotelPicture', models.ImageField(null=True, upload_to='static/hotelspic/')),
                ('hotelLocation', models.CharField(max_length=500, null=True)),
                ('hotelDescription', models.TextField(null=True)),
                ('hotelPrice', models.IntegerField(null=True)),
                ('hotelGrade', models.CharField(max_length=100, null=True)),
                ('hotelRating', models.FloatField(max_length=15, null=True)),
                ('hotelReviews', models.IntegerField(null=True)),
            ],
        ),
    ]
