# Generated by Django 3.2.4 on 2023-12-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotelPrice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
