# Generated by Django 3.2.4 on 2023-12-18 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_hotels_hotelprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelPicture1', models.ImageField(null=True, upload_to='static/hotelspic/')),
                ('hotelPicture2', models.ImageField(null=True, upload_to='static/hotelspic/')),
                ('hotelPicture3', models.ImageField(null=True, upload_to='static/hotelspic/')),
                ('hotelPicture4', models.ImageField(null=True, upload_to='static/hotelspic/')),
                ('hotelPicture5', models.ImageField(null=True, upload_to='static/hotelspic/')),
                ('hotelPicture6', models.ImageField(null=True, upload_to='static/hotelspic/')),
                ('hotelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hotels')),
            ],
        ),
    ]
