# Generated by Django 3.2.4 on 2023-12-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelLocation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelPicture',
            field=models.ImageField(null=True, upload_to='static/hotelspic/'),
        ),
    ]
