# Generated by Django 3.2.4 on 2024-02-20 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20231218_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='Destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.explore'),
        ),
    ]
