# Generated by Django 3.2.4 on 2024-02-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_hotels_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explore',
            old_name='ename',
            new_name='Destination',
        ),
    ]
