# Generated by Django 3.2.4 on 2024-02-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_rename_ename_explore_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explore',
            old_name='Destination',
            new_name='ename',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='Destination',
        ),
    ]
