# Generated by Django 3.2.4 on 2024-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20240220_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardHolderName', models.CharField(max_length=100, null=True)),
                ('cardType', models.CharField(max_length=100, null=True)),
                ('cardNumber', models.IntegerField(null=True)),
                ('expirationDate', models.DateField(null=True)),
                ('cvvNum', models.IntegerField(null=True)),
                ('OTP', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('countaryName', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('fullGuestName', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
