# Generated by Django 3.2.4 on 2024-02-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_paymentdetails_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='Destination',
        ),
    ]
