# Generated by Django 3.2.4 on 2024-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20240221_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
