# Generated by Django 3.2.4 on 2024-02-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20240221_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='countaryName',
            new_name='countryName',
        ),
    ]
